DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'UserRole') THEN
    CREATE TYPE "UserRole" AS ENUM ('USER', 'ADMIN');
  END IF;
END $$;

ALTER TYPE "LogoSource" ADD VALUE IF NOT EXISTS 'UPLOAD';

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "role" "UserRole" NOT NULL DEFAULT 'USER';

ALTER TABLE "CurrentPrice"
ADD COLUMN IF NOT EXISTS "regular_market_price" DECIMAL(18, 6),
ADD COLUMN IF NOT EXISTS "extended_market_price" DECIMAL(18, 6),
ADD COLUMN IF NOT EXISTS "last_price" DECIMAL(18, 6),
ADD COLUMN IF NOT EXISTS "previous_close" DECIMAL(18, 6),
ADD COLUMN IF NOT EXISTS "display_price" DECIMAL(18, 6),
ADD COLUMN IF NOT EXISTS "price_source" TEXT,
ADD COLUMN IF NOT EXISTS "price_updated_at" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "is_stale" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Holding"
ADD COLUMN IF NOT EXISTS "regular_market_price" DECIMAL(18, 6),
ADD COLUMN IF NOT EXISTS "extended_market_price" DECIMAL(18, 6),
ADD COLUMN IF NOT EXISTS "last_price" DECIMAL(18, 6),
ADD COLUMN IF NOT EXISTS "previous_close" DECIMAL(18, 6),
ADD COLUMN IF NOT EXISTS "display_price" DECIMAL(18, 6),
ADD COLUMN IF NOT EXISTS "price_source" TEXT,
ADD COLUMN IF NOT EXISTS "price_updated_at" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "is_stale" BOOLEAN NOT NULL DEFAULT false;
